### ISSUE TITLE
Incorrect handling of left square bracket inside character classes

### ISSUE THREAD

**Issue by ju1ius** [hoaproject/Regex#32]
Hi,

Parsing the pattern `[[]` throws `Unexpected token "[" (class_) at line 1 and column 2`.
Left square brackets don't need escaping inside character classes, so they should produce a literal token with the value "[".

**Comment by Hywan** [comment]
https://github.com/hoaproject/Regex/commit/ce7fd7b5a26bdeeee7c8385fd7cabd5686e9af37 fixes the issue. Can you test on your use case please?
